### PR TITLE
Allow disabling of server requirement

### PR DESCRIPTION
**Pull request by chris-forbes-1**
I've added an extra field into the TSQLEasy settings which lets you completely disable the requirement for network connectivity. I really needed this plugin just for syntax highlighting :)  I don't know if it will be of any use but if you think it's any good it's all yours.

Thanks,
Chris

### CODE REVIEW

**Comment by chris-forbes-1** [comment]
The change to the TSQL.tmLanguage was a syntax highlighting bug I found which highlighted 'proc' in the word 'procedure'

**Comment by tosher** [comment]
<pre>
empty driver value for work offline without completions
</pre>
Not works?

**Comment by tosher** [comment]
just for syntax highlighting :)
https://github.com/wbond/sublime-sql-tmlanguage

**Comment by chris-forbes-1** [comment]
The  empty driver does work, I just  felt  that this was almost a workaround rather than functionality hence adding an explicit configuration point made it easier to understand.

**Comment by tosher** [comment]
It's not workaround, with this option you can set in the settings:
* Empty server (Offline)
* Real server (or several)
After that, you can switch between offline and online modes by command **Server select**, without changing settings.

**Comment by chris-forbes-1** [comment]
Ah sorry I must have missed those :pensive:, I think the only thing that could be salvageable is the TSQL.tmLanguage for the highlighting bug

**Comment by tosher** [comment]
Done, thanks for fix!

**Pull request closed without merging**
