### PR TITLE
Ignore accents, use schema and bug workaround (appear only sometimes)

### PR DESCRIPTION
**Pull request by caiohamamura**
* Encode returned unicode data from database with encoding set by user in settings.
* Use schema for opening procedures: it will use the [SCHEMA].[PROCEDURE] name instead of only the [PROCEDURE] name.
* Bug workaround: when loading the file into sublime, sometimes it would fail to show the file contents because the file was closed before sublime accesses, now it will use a 100 ms delay. 
* Use schema identifiers before table name if present and display only tables within that schema, else use default schema.

### CODE REVIEW

**Comment by tosher** [comment]
Thank you, i'll see the changes.

**Comment by caiohamamura** [comment]
Ok.

I've done some changes now, because the encoding issues occur only in
Sublime 2, so I added a flag to check the version before processing
encodings.

Caio Hamamura

2015-07-28 10:39 GMT-03:00 tosher <notifications@github.com>:

**Comment by caiohamamura** [comment]
BTW, thanks man, it is a great plugin! You've done a nice job, if I had a
little more time I would like to help in including Functions and
Procedures, also it would be nice to autocomplete TSQL keywords.

Caio Hamamura

2015-07-28 11:17 GMT-03:00 Caio Hamamura <caiohamamura@gmail.com>:

**Comment by tosher** [comment]
I want to split your changes into parts by functionality:
* Trusted connection - i want to implement this with some differences.. without specific values in the settings. 
* Schemas - as is with small cosmetics..
* Delay on loading - as is... it's exists on Linux or Windows?
* Encodings. I think this problem must be solved in another way.. Please, tell me which encodings used in your procedures, which database collation is used, and value of **fallback_encoding** in Sublime? 
P.S. **te_encodings** - is an encoding of the data in database, not in sublime.

**Comment by caiohamamura** [comment]
Trusted connection: I know it is a bad implementation, I made it that way
because I really needed it.

Delay: occurs in windows sublime 2.
Encodings: the encoding problem occurs in sublime 2 only, it is a Python 2
issue with cp1252. Python will not return errors but accents are replaced
with different characters. My database is using cp1252 collation
latin1_general_ci_ai.

Actually with the implementation I made it won't ignore accents, it will
return the characters as expected instead. It is a known flaw of Python 2
that you have to explicitly encode Unicode chars to user console/UI
codepage.
Em 06/08/2015 19:44, "tosher" <notifications@github.com> escreveu:

**Comment by tosher** [comment]
I'm pushed several commits. Can you check what works fine and what not?

**Comment by caiohamamura** [comment]
Tosher, regular select are returning accents normally, but I can't even open any object from server, it is returning:

    AttributeError: SQLCon instance has no attribute 'sqlconnnection'
    Traceback (most recent call last):
      File ".\sublime_plugin.py", line 362, in run_
      File ".\tsqleasy.py", line 443, in run
    AttributeError: SQLCon instance has no attribute 'sqlconnnection'

**Comment by tosher** [comment]
Ohh, typo sqlco**nnn**ection :)
Fixed.

**Pull request closed without merging**
